#include <stdio.h>
#include <string.h>

typedef struct {
    char* name;
    char* region;
    char* budget;
    char* duration;
    char* tripType;
    char* description;
} Package;

#define PACKAGE_COUNT 243

Package packages[PACKAGE_COUNT] = {
    { "Kappil Beach Getaway (low/three)", "beach", "low", "three", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (low/six)", "beach", "low", "six", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (low/seven)", "beach", "low", "seven", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (medium/three)", "beach", "medium", "three", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (medium/six)", "beach", "medium", "six", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (medium/seven)", "beach", "medium", "seven", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (high/three)", "beach", "high", "three", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (high/six)", "beach", "high", "six", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (high/seven)", "beach", "high", "seven", "solo", "Quiet budget beach day out. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (low/three)", "beach", "low", "three", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (low/six)", "beach", "low", "six", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (low/seven)", "beach", "low", "seven", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (medium/three)", "beach", "medium", "three", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (medium/six)", "beach", "medium", "six", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (medium/seven)", "beach", "medium", "seven", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (high/three)", "beach", "high", "three", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (high/six)", "beach", "high", "six", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Tangasseri Lighthouse Stay (high/seven)", "beach", "high", "seven", "solo", "Heritage seafront experience. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (low/three)", "beach", "low", "three", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (low/six)", "beach", "low", "six", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (low/seven)", "beach", "low", "seven", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (medium/three)", "beach", "medium", "three", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (medium/six)", "beach", "medium", "six", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (medium/seven)", "beach", "medium", "seven", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (high/three)", "beach", "high", "three", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (high/six)", "beach", "high", "six", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Thirumullavaram Sunrise (high/seven)", "beach", "high", "seven", "solo", "Early morning coastal serenity. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (low/three)", "hill", "low", "three", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (low/six)", "hill", "low", "six", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (low/seven)", "hill", "low", "seven", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (medium/three)", "hill", "medium", "three", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (medium/six)", "hill", "medium", "six", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (medium/seven)", "hill", "medium", "seven", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (high/three)", "hill", "high", "three", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (high/six)", "hill", "high", "six", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Ponmudi Hills Retreat (high/seven)", "hill", "high", "seven", "solo", "Tea‑garden walks & waterfall trek. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (low/three)", "hill", "low", "three", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (low/six)", "hill", "low", "six", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (low/seven)", "hill", "low", "seven", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (medium/three)", "hill", "medium", "three", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (medium/six)", "hill", "medium", "six", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (medium/seven)", "hill", "medium", "seven", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (high/three)", "hill", "high", "three", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (high/six)", "hill", "high", "six", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Nelliyampathy Coffee Circuit (high/seven)", "hill", "high", "seven", "solo", "Plantation tours & birdwatching. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (low/three)", "hill", "low", "three", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (low/six)", "hill", "low", "six", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (low/seven)", "hill", "low", "seven", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (medium/three)", "hill", "medium", "three", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (medium/six)", "hill", "medium", "six", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (medium/seven)", "hill", "medium", "seven", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (high/three)", "hill", "high", "three", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (high/six)", "hill", "high", "six", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Peermade Spice Sojourn (high/seven)", "hill", "high", "seven", "solo", "Spice estate tour & local cuisine. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (low/three)", "backwater", "low", "three", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (low/six)", "backwater", "low", "six", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (low/seven)", "backwater", "low", "seven", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (medium/three)", "backwater", "medium", "three", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (medium/six)", "backwater", "medium", "six", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (medium/seven)", "backwater", "medium", "seven", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (high/three)", "backwater", "high", "three", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (high/six)", "backwater", "high", "six", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Munroe Island Homestay (high/seven)", "backwater", "high", "seven", "solo", "Canal cruise + village life. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (low/three)", "backwater", "low", "three", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (low/six)", "backwater", "low", "six", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (low/seven)", "backwater", "low", "seven", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (medium/three)", "backwater", "medium", "three", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (medium/six)", "backwater", "medium", "six", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (medium/seven)", "backwater", "medium", "seven", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (high/three)", "backwater", "high", "three", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (high/six)", "backwater", "high", "six", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Pathiramanal Birdwatching (high/seven)", "backwater", "high", "seven", "solo", "Ferry to bird sanctuary island. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (low/three)", "backwater", "low", "three", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (low/six)", "backwater", "low", "six", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (low/seven)", "backwater", "low", "seven", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (medium/three)", "backwater", "medium", "three", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (medium/six)", "backwater", "medium", "six", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (medium/seven)", "backwater", "medium", "seven", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (high/three)", "backwater", "high", "three", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (high/six)", "backwater", "high", "six", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kakkathuruthu Village Trail (high/seven)", "backwater", "high", "seven", "solo", "Off‑beat fishing village visit. Perfect for independent travellers seeking local immersion." },
    { "Kappil Beach Getaway (low/three)", "beach", "low", "three", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (low/six)", "beach", "low", "six", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (low/seven)", "beach", "low", "seven", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (medium/three)", "beach", "medium", "three", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (medium/six)", "beach", "medium", "six", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (medium/seven)", "beach", "medium", "seven", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (high/three)", "beach", "high", "three", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (high/six)", "beach", "high", "six", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (high/seven)", "beach", "high", "seven", "couple", "Quiet budget beach day out. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (low/three)", "beach", "low", "three", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (low/six)", "beach", "low", "six", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (low/seven)", "beach", "low", "seven", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (medium/three)", "beach", "medium", "three", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (medium/six)", "beach", "medium", "six", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (medium/seven)", "beach", "medium", "seven", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (high/three)", "beach", "high", "three", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (high/six)", "beach", "high", "six", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Tangasseri Lighthouse Stay (high/seven)", "beach", "high", "seven", "couple", "Heritage seafront experience. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (low/three)", "beach", "low", "three", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (low/six)", "beach", "low", "six", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (low/seven)", "beach", "low", "seven", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (medium/three)", "beach", "medium", "three", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (medium/six)", "beach", "medium", "six", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (medium/seven)", "beach", "medium", "seven", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (high/three)", "beach", "high", "three", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (high/six)", "beach", "high", "six", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Thirumullavaram Sunrise (high/seven)", "beach", "high", "seven", "couple", "Early morning coastal serenity. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (low/three)", "hill", "low", "three", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (low/six)", "hill", "low", "six", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (low/seven)", "hill", "low", "seven", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (medium/three)", "hill", "medium", "three", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (medium/six)", "hill", "medium", "six", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (medium/seven)", "hill", "medium", "seven", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (high/three)", "hill", "high", "three", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (high/six)", "hill", "high", "six", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Ponmudi Hills Retreat (high/seven)", "hill", "high", "seven", "couple", "Tea‑garden walks & waterfall trek. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (low/three)", "hill", "low", "three", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (low/six)", "hill", "low", "six", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (low/seven)", "hill", "low", "seven", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (medium/three)", "hill", "medium", "three", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (medium/six)", "hill", "medium", "six", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (medium/seven)", "hill", "medium", "seven", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (high/three)", "hill", "high", "three", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (high/six)", "hill", "high", "six", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Nelliyampathy Coffee Circuit (high/seven)", "hill", "high", "seven", "couple", "Plantation tours & birdwatching. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (low/three)", "hill", "low", "three", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (low/six)", "hill", "low", "six", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (low/seven)", "hill", "low", "seven", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (medium/three)", "hill", "medium", "three", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (medium/six)", "hill", "medium", "six", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (medium/seven)", "hill", "medium", "seven", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (high/three)", "hill", "high", "three", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (high/six)", "hill", "high", "six", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Peermade Spice Sojourn (high/seven)", "hill", "high", "seven", "couple", "Spice estate tour & local cuisine. Romantic experience tailored for two." },
    { "Munroe Island Homestay (low/three)", "backwater", "low", "three", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (low/six)", "backwater", "low", "six", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (low/seven)", "backwater", "low", "seven", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (medium/three)", "backwater", "medium", "three", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (medium/six)", "backwater", "medium", "six", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (medium/seven)", "backwater", "medium", "seven", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (high/three)", "backwater", "high", "three", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (high/six)", "backwater", "high", "six", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Munroe Island Homestay (high/seven)", "backwater", "high", "seven", "couple", "Canal cruise + village life. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (low/three)", "backwater", "low", "three", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (low/six)", "backwater", "low", "six", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (low/seven)", "backwater", "low", "seven", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (medium/three)", "backwater", "medium", "three", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (medium/six)", "backwater", "medium", "six", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (medium/seven)", "backwater", "medium", "seven", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (high/three)", "backwater", "high", "three", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (high/six)", "backwater", "high", "six", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Pathiramanal Birdwatching (high/seven)", "backwater", "high", "seven", "couple", "Ferry to bird sanctuary island. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (low/three)", "backwater", "low", "three", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (low/six)", "backwater", "low", "six", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (low/seven)", "backwater", "low", "seven", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (medium/three)", "backwater", "medium", "three", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (medium/six)", "backwater", "medium", "six", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (medium/seven)", "backwater", "medium", "seven", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (high/three)", "backwater", "high", "three", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (high/six)", "backwater", "high", "six", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kakkathuruthu Village Trail (high/seven)", "backwater", "high", "seven", "couple", "Off‑beat fishing village visit. Romantic experience tailored for two." },
    { "Kappil Beach Getaway (low/three)", "beach", "low", "three", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (low/six)", "beach", "low", "six", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (low/seven)", "beach", "low", "seven", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (medium/three)", "beach", "medium", "three", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (medium/six)", "beach", "medium", "six", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (medium/seven)", "beach", "medium", "seven", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (high/three)", "beach", "high", "three", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (high/six)", "beach", "high", "six", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Kappil Beach Getaway (high/seven)", "beach", "high", "seven", "group", "Quiet budget beach day out. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (low/three)", "beach", "low", "three", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (low/six)", "beach", "low", "six", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (low/seven)", "beach", "low", "seven", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (medium/three)", "beach", "medium", "three", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (medium/six)", "beach", "medium", "six", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (medium/seven)", "beach", "medium", "seven", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (high/three)", "beach", "high", "three", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (high/six)", "beach", "high", "six", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Tangasseri Lighthouse Stay (high/seven)", "beach", "high", "seven", "group", "Heritage seafront experience. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (low/three)", "beach", "low", "three", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (low/six)", "beach", "low", "six", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (low/seven)", "beach", "low", "seven", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (medium/three)", "beach", "medium", "three", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (medium/six)", "beach", "medium", "six", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (medium/seven)", "beach", "medium", "seven", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (high/three)", "beach", "high", "three", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (high/six)", "beach", "high", "six", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Thirumullavaram Sunrise (high/seven)", "beach", "high", "seven", "group", "Early morning coastal serenity. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (low/three)", "hill", "low", "three", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (low/six)", "hill", "low", "six", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (low/seven)", "hill", "low", "seven", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (medium/three)", "hill", "medium", "three", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (medium/six)", "hill", "medium", "six", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (medium/seven)", "hill", "medium", "seven", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (high/three)", "hill", "high", "three", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (high/six)", "hill", "high", "six", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Ponmudi Hills Retreat (high/seven)", "hill", "high", "seven", "group", "Tea‑garden walks & waterfall trek. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (low/three)", "hill", "low", "three", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (low/six)", "hill", "low", "six", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (low/seven)", "hill", "low", "seven", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (medium/three)", "hill", "medium", "three", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (medium/six)", "hill", "medium", "six", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (medium/seven)", "hill", "medium", "seven", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (high/three)", "hill", "high", "three", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (high/six)", "hill", "high", "six", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Nelliyampathy Coffee Circuit (high/seven)", "hill", "high", "seven", "group", "Plantation tours & birdwatching. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (low/three)", "hill", "low", "three", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (low/six)", "hill", "low", "six", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (low/seven)", "hill", "low", "seven", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (medium/three)", "hill", "medium", "three", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (medium/six)", "hill", "medium", "six", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (medium/seven)", "hill", "medium", "seven", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (high/three)", "hill", "high", "three", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (high/six)", "hill", "high", "six", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Peermade Spice Sojourn (high/seven)", "hill", "high", "seven", "group", "Spice estate tour & local cuisine. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (low/three)", "backwater", "low", "three", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (low/six)", "backwater", "low", "six", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (low/seven)", "backwater", "low", "seven", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (medium/three)", "backwater", "medium", "three", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (medium/six)", "backwater", "medium", "six", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (medium/seven)", "backwater", "medium", "seven", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (high/three)", "backwater", "high", "three", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (high/six)", "backwater", "high", "six", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Munroe Island Homestay (high/seven)", "backwater", "high", "seven", "group", "Canal cruise + village life. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (low/three)", "backwater", "low", "three", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (low/six)", "backwater", "low", "six", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (low/seven)", "backwater", "low", "seven", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (medium/three)", "backwater", "medium", "three", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (medium/six)", "backwater", "medium", "six", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (medium/seven)", "backwater", "medium", "seven", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (high/three)", "backwater", "high", "three", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (high/six)", "backwater", "high", "six", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Pathiramanal Birdwatching (high/seven)", "backwater", "high", "seven", "group", "Ferry to bird sanctuary island. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (low/three)", "backwater", "low", "three", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (low/six)", "backwater", "low", "six", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (low/seven)", "backwater", "low", "seven", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (medium/three)", "backwater", "medium", "three", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (medium/six)", "backwater", "medium", "six", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (medium/seven)", "backwater", "medium", "seven", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (high/three)", "backwater", "high", "three", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (high/six)", "backwater", "high", "six", "group", "Off‑beat fishing village visit. Fun group activities and shared experiences." },
    { "Kakkathuruthu Village Trail (high/seven)", "backwater", "high", "seven", "group", "Off��beat fishing village visit. Fun group activities and shared experiences." },
};

char result[2048]; // To store final result

char* recommend(char* region, char* budget, char* duration, char* tripType) {
    strcpy(result, ""); // Clear previous
    int count = 0;
    for (int i = 0; i < PACKAGE_COUNT; i++) {
        if (strcmp(packages[i].region, region) == 0 &&
            strcmp(packages[i].budget, budget) == 0 &&
            strcmp(packages[i].duration, duration) == 0 &&
            strcmp(packages[i].tripType, tripType) == 0) {

            char buffer[512];
            sprintf(buffer, "%s|%s\n", packages[i].name, packages[i].description);
            strcat(result, buffer);
            count++;
            if (count == 3) break;
        }
    }

    if (count == 0) {
        strcpy(result, "No matches found.|Try adjusting your options.");
    }

    return result;
}
